package toyc;

enum TokenKind {
    ID, NUMBER,
    CONST, INT, VOID, IF, ELSE, WHILE, BREAK, CONTINUE, RETURN,
    PLUS, MINUS, STAR, SLASH, PERCENT, BANG,
    LT, GT, LE, GE, EQEQ, NEQ, ANDAND, OROR,
    ASSIGN, SEMI, COMMA, LPAREN, RPAREN, LBRACE, RBRACE, EOF
}
